experiment:
    root: '/workspace/experiments/exp_scan/'
    writer_root: '/workspace/experiments/runs_scan_v3/'
data:
    path: '/workspace/datasets/k.mazur/ScanObjectNN/h5_files/main_split/training_objectdataset_augmentedrot_scale75.h5'
    path_val: '/workspace/datasets/k.mazur/ScanObjectNN/h5_files/main_split/test_objectdataset_augmentedrot_scale75.h5'
    batch_size: 8
    batch_size_val: 8
    num_workers: 4
    num_points: 2048
    normalize: True
    center: True
model:
    generator: './model_zoo/scanobject/classifier.py'
train:
    seg_weight: !!float 0.5
    show_each: 500
    save_each: 25000
    num_epochs: 600
    save_each_epoch: 10
    val_step: 1
    optimizer:
        type: 'Adam'
        lr: !!float 1e-3
        betas: [!!float 0.9, !!float 0.999]
        weight_decay: !!float 0
    scheduler:
       type: 'StepLR'
       gamma: !!float 0.7
       step_size: 25000